// <auto-generated />
using System;
using ConfigurationManagement.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConfigurationManagement.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ConfigurationModels.Configuration", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfigurationAlertesID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfigurationCommercialeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfigurationCompteID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfigurationPagePresentoireID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfigurationProfilID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfigurationPubliciteesID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfigurationRechercheID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ConfigurationAlertesID");

                    b.HasIndex("ConfigurationCommercialeID");

                    b.HasIndex("ConfigurationCompteID");

                    b.HasIndex("ConfigurationPagePresentoireID");

                    b.HasIndex("ConfigurationProfilID");

                    b.HasIndex("ConfigurationPubliciteesID");

                    b.HasIndex("ConfigurationRechercheID");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("ConfigurationModels.ConfigurationAlertes", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("ConfigurationAlertes");
                });

            modelBuilder.Entity("ConfigurationModels.ConfigurationCommerciale", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("ConfigurationCommerciales");
                });

            modelBuilder.Entity("ConfigurationModels.ConfigurationCompte", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("ConfigurationComptes");
                });

            modelBuilder.Entity("ConfigurationModels.ConfigurationPagePresentoire", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("ConfigurationPagePresentoires");
                });

            modelBuilder.Entity("ConfigurationModels.ConfigurationProfil", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("ConfigurationProfils");
                });

            modelBuilder.Entity("ConfigurationModels.ConfigurationPublicitees", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("ConfigurationPublicitees");
                });

            modelBuilder.Entity("ConfigurationModels.ConfigurationRecherche", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("ConfigurationRecherches");
                });

            modelBuilder.Entity("ConfigurationModels.Configuration", b =>
                {
                    b.HasOne("ConfigurationModels.ConfigurationAlertes", "ConfigurationAlertes")
                        .WithMany()
                        .HasForeignKey("ConfigurationAlertesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConfigurationModels.ConfigurationCommerciale", "ConfigurationCommerciale")
                        .WithMany()
                        .HasForeignKey("ConfigurationCommercialeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConfigurationModels.ConfigurationCompte", "ConfigurationCompte")
                        .WithMany()
                        .HasForeignKey("ConfigurationCompteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConfigurationModels.ConfigurationPagePresentoire", "ConfigurationPagePresentoire")
                        .WithMany()
                        .HasForeignKey("ConfigurationPagePresentoireID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConfigurationModels.ConfigurationProfil", "ConfigurationProfil")
                        .WithMany()
                        .HasForeignKey("ConfigurationProfilID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConfigurationModels.ConfigurationPublicitees", "ConfigurationPublicitees")
                        .WithMany()
                        .HasForeignKey("ConfigurationPubliciteesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConfigurationModels.ConfigurationRecherche", "ConfigurationRecherche")
                        .WithMany()
                        .HasForeignKey("ConfigurationRechercheID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigurationAlertes");

                    b.Navigation("ConfigurationCommerciale");

                    b.Navigation("ConfigurationCompte");

                    b.Navigation("ConfigurationPagePresentoire");

                    b.Navigation("ConfigurationProfil");

                    b.Navigation("ConfigurationPublicitees");

                    b.Navigation("ConfigurationRecherche");
                });
#pragma warning restore 612, 618
        }
    }
}
