// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaiementManagementApi.Contexts;

#nullable disable

namespace PaiementManagementApi.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220916193759_AbonnementTabForMassTransit")]
    partial class AbonnementTabForMassTransit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PaiementManagement.AccountReceiver", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("AccountReceiver");
                });

            modelBuilder.Entity("PaiementManagement.AccountSender", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("AccountSender");
                });

            modelBuilder.Entity("PaiementManagement.Paiement", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountReceiverID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountSenderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaiementMethod")
                        .HasColumnType("int");

                    b.Property<int>("StatusPaiement")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AccountReceiverID");

                    b.HasIndex("AccountSenderID");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("PaiementModels.Abonnement", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AbonnementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Abonnements");
                });

            modelBuilder.Entity("PaiementManagement.Paiement", b =>
                {
                    b.HasOne("PaiementManagement.AccountReceiver", "AccountReceiver")
                        .WithMany()
                        .HasForeignKey("AccountReceiverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaiementManagement.AccountSender", "AccountSender")
                        .WithMany()
                        .HasForeignKey("AccountSenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountReceiver");

                    b.Navigation("AccountSender");
                });
#pragma warning restore 612, 618
        }
    }
}
