// <auto-generated />
using System;
using AbonnementManagementAPI.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbonnementManagementAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220913234437_CreateInitial")]
    partial class CreateInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AbonnementModels.Abonnement", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AbonnementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodeLivraison")
                        .HasColumnType("int");

                    b.Property<int>("PeriodePaiement")
                        .HasColumnType("int");

                    b.Property<bool>("RepetitionAutomatique")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Abonnements");
                });
#pragma warning restore 612, 618
        }
    }
}
